# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8d9113cf62a22697016107f3aac61f4f0b740132f284ecc4f2a6bc14dae822aa38e7f9e2983030ecca924513fdb92a9afe52e4d0c64208c2dd541870867b336e

test:
  secret_key_base: f6b9e0cc1ab5c5b90751bffad860e76b5f0daecfff2131fb0bd67fa370a727fb544dfcdac935e63f18123fbe73a6665b9fe0482185c36dd115f603bcdcba389e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
